### ISSUE TITLE
Should there be support for a .frozen property?

### ISSUE THREAD

**Issue by astorije** [astorije/chai-immutable#13]
I found myself in the need to test if an object was [frozen](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isFrozen).

Right now, one has to do:

```js
expect(Object.isFrozen(obj)).to.be.true;
```

which is not very pretty. I came up with a simple helper to allow the following syntax:

```js
expect(obj).to.be.frozen;
```

I am not sure if this helper should be part of this project. On one end, it's not using [Immutable](https://github.com/facebook/immutable-js/), but on the other end, [`Object#freeze()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) is the closest we have to immutable objects in JS...

So, should I include it here? Any other suggestion?

**Comment by zanuka** [comment]
yes, would be handy

**Comment by astorije** [comment]
Alright, it's on the todolist then :-)

**Comment by astorije** [comment]
Well... [I did it](https://github.com/astorije/chai-immutable/compare/1440a1fa5b97d02f82ca4350862a5b78412c7f67...48241e86558291a21dbfd0f462291d90f3b2f9e7), and then [I un-did it](https://github.com/astorije/chai-immutable/commit/252eaf420e9cd762765b266e239303a928eed462) because it has [just been added to Chai 3.1.0](https://github.com/chaijs/chai/releases/tag/3.1.0).

Please use this assertion then. Makes more sense to find it there anyway!
