### ISSUE TITLE
1.1.0 Broken in npm registry it seems

### ISSUE THREAD

**Issue by steida** [astorije/chai-immutable#17]

**Comment by grabbou** [comment]
checksum invalid, so looks like the package might be broken?

**Comment by astorije** [comment]
Argh, [again](https://github.com/astorije/chai-immutable/issues/15)? I am investigating to see what's going on...

**Comment by astorije** [comment]
I reported an issue on npm (https://github.com/npm/npm/issues/8822) so stay tuned. Thanks for the report @steida and @grabbou!

**Comment by grabbou** [comment]
Awesome! I hope we won't need to add post-publish tests anytime in the future :D

**Comment by astorije** [comment]
I'm not sure what to do here, and if it's a one-time error or if anytime I'll publish through Travis CI the bug will happen.
I'll leave another day or so to the npm team to look into it, but after that I'll try to manually release a version 1.1.1 as I understand it's a pain for you guys. Sorry about that!

**Comment by astorije** [comment]
And now we have https://github.com/travis-ci/travis-ci/issues/4197, perfect...

**Comment by astorije** [comment]
Nevermind, I manually published [version 1.1.1](https://github.com/astorije/chai-immutable/releases/tag/v1.1.1) and made sure this one works. So things should be solved

I'll leave this issue open until I know what happened on version 1.1.0 and until I unpublish it. I'll leave it published in case it's useful to the npm guys.

**Comment by grabbou** [comment]
I think it's already explained and can be closed. Issue was with Node version.

**Comment by astorije** [comment]
Indeed, [as explained by @iarna](https://github.com/npm/npm/issues/8822#issuecomment-119431682).

Unless this gets fixed on the [Travis CI](https://github.com/travis-ci/travis-ci/issues/4205) end, I might have to remove version 0.11 from the `.travis.yml` file before the next release...
