### ISSUE TITLE
JSCS rules on comments are too strict

### ISSUE THREAD

**Issue by astorije** [astorije/chai-immutable#19]
According to [this comment](https://github.com/astorije/chai-immutable/pull/18#discussion_r34215616) by @matthewwithanm, it's not possible to leave comments like:

```js
// Lorem ipsum dolor sit amet
// consectetur adipiscing elit
```

But only:

```js
/*
 * Lorem ipsum dolor sit amet
 * consectetur adipiscing elit
 */
```

Which is quite painful! I think I went a bit too far on comment conventions and I need to relax them a bit...

**Comment by matthewwithanm** [comment]
IIRC The linting error was about surrounding whitespace and I wasn't able to find something that made it happy (except the star style).
