### ISSUE TITLE
chai-immutable@2.1.0" has incorrect peer dependency "immutable@^3.0.0".

### ISSUE THREAD

**Issue by pbadenski** [astorije/chai-immutable#287]

**Comment by astorije** [comment]
What version of `immutable` are you using?

**Comment by pbadenski** [comment]
Using `4.0.0-rc.12`

**Comment by astorije** [comment]
That makes sense. v4 will be supported when it's out, right now v3 is supported. RC versions have not been tested against chai-immutable, hence this warning.

**Comment by pbadenski** [comment]
That's fair enough, however immutablejs has been stuck in 4.0.0-rc for 2.5 years now with no clear path of 4.0.0 so far...
