### ISSUE TITLE
latest immutablejs support(Is this library even alive?)

### ISSUE THREAD

**Issue by josiahmokob0** [astorije/chai-immutable#301]
https://github.com/astorije/chai-immutable/blob/dfb3d1cf73774d566efe7a70cd8e7eaa4e5b6786/package.json#L46

It doesn't work with latest version of  immutablejs. Is there a workaround for this?

**Comment by astorije** [comment]
What error do you encounter? v3 is the latest stable, v4 is in RC

**Comment by josiahmokob0** [comment]
Ok, that makes sense. I am using v4

**Comment by astorije** [comment]
I believe it should work fine with v4 as well. Let me know if you're running into issues.

**Comment by josiahmokob0** [comment]
Thanks @astorije . will keep you updated.

**Comment by pbadenski** [comment]
@astorije could you perhaps update the version specifier to silence the warning?
