### ISSUE TITLE
Add support for chai-as-promised

### ISSUE THREAD

**Issue by jakubzitny** [astorije/chai-immutable#32]
I have some promises returning collections from immutable.js.
It'd be nice to expect the promised values with [chai-as-promised](http://chaijs.com/plugins/chai-as-promised).

Something like:
```js
expect(Promise.resolve(immutable.List())).to.eventually.be.empty
```

**Comment by astorije** [comment]
Hey @jakubzitny, thanks for bringing that up!

As a matter of fact, I have used chai-immutable with chai-as-promised before. Look at [this test](https://github.com/w3c/echidna/blob/edb6e08ec0b95b627a32e132373a9f322c7c9e68/test/test.js#L99) for example. Note however that this relies on chai-as-promised being loaded after chai-immutable (or any other plugins you want to "promisify", for that matter), as [shown at the beginning](https://github.com/w3c/echidna/blob/edb6e08ec0b95b627a32e132373a9f322c7c9e68/test/test.js#L10-L16).

Could you confirm this answers your issue? Do you see anything we can add to chai-immutable in this regard?

**Comment by jakubzitny** [comment]
Hi, thanks for the reply :)

It really works when I load chai-as-promised at the end, great. Actually I did think about this but somehow I forgot to try loading it like this. Maybe it would help to mention it in the Installation part of README. Also some examples of chai-immutable with other plugins could be helpful.

**Comment by astorije** [comment]
Thanks @jakubzitny, I'll add a mention about loading chai-immutable before chai-as-promised in the README of this project, although I believe this has more its place in the README of chai-as-promised.

I won't come up with examples of using with other plugins as I'm not using any myself, but I'd be happy to discuss such examples here before adding them to the README :-)

**Comment by astorije** [comment]
I have added a paragraph in the doc and submitted it as a PR (#38) so that you can tell me what you think before merging it. See you there!
