### ISSUE TITLE
Comparison of Lists fails on different internal properties

### ISSUE THREAD

**Issue by jasonquick** [astorije/chai-immutable#33]
Hello. Apologies if this has been addressed or if I've done something foolish, but I'm pretty sure this is legitimately unexpected behavior.

I'm using Immutable 3.7.5, Chai 3.4.1 and chai-immutable 1.5.3 with Node 4.2.2 on Windoze. Here's what I'm seeing:

```javascript
    describe('A List', () => {

        function addListItem(currentState,item) {
            // Push item onto currentState and return the new state
            return currentState.push(item);
        }

        it('is immutable', () => {
            let state = List.of('Bar','Foo');
            let nextState = addListItem(state, 'Baz');

            expect(nextState).to.equal(List.of(
                'Bar',
                'Foo',
                'Baz'
            ));
        });

    });
```

I expect this test to pass, however:

```
AssertionError: expected List [ "Bar", "Foo", "Baz" ] to equal List [ "Bar", "Foo", "Baz" ]
      + expected - actual

       {
      -  "__altered": true
      +  "__altered": false
         "__hash": [undefined]
         "__ownerID": [undefined]
         "_capacity": 3
         "_level": 5
             "Bar"
             "Foo"
             "Baz"
           ]
      -    "ownerID": {}
      +    "ownerID": [undefined]
         }
         "size": 3
       }
```

These internal implementation properties "ownerID" and "__altered" are resulting in a failed assertion that I  believe should pass.

**Comment by jasonquick** [comment]
How embarrassing...I was (obviously?) not including chaiImmutable in the place I was trying to use it. 

I was suffering from insufficient caffeination. Please don't take my keyboard away.

**Comment by astorije** [comment]
Ah ah ah, your keyboard is safe :-)

No worries for the issue. Actually, looking at the output, it's not that obvious that you forgot to `chai.use(chaiImmutable)` (but there is nothing we can do to improve that here), so it's actually a good thing for those who will have the same output for the same reason.
Thanks for closing this by giving the explanation!
