### ISSUE TITLE
Publish new version!

### ISSUE THREAD

**Issue by txgruppi** [astorije/chai-immutable#44]
There are several commits which are not published to NPM.

One really important to me is https://github.com/astorije/chai-immutable/commit/7c8697f131ac3a86af2012cc83274855627d17e4

Can you please publish them?

Thank you.

**Comment by astorije** [comment]
Hey @txgruppi, my bad, I did not manage to spend too much time on this project lately, but I should have released after merging the PR associated to this commit.
This is now done in [tag `v1.5.4`](https://github.com/astorije/chai-immutable/releases/tag/v1.5.4) and accessible on npm.

Thanks for the reminder!

**Comment by txgruppi** [comment]
Sorry for the "cold" message, I had quite a busy day.

I just wanted to remind you to publish, in the case you had forgotten.

Thank you so much :)

**Comment by astorije** [comment]
Don't worry, I didn't take it like that.
If anything, I'm happy people are using my modest project :-)
