### ISSUE TITLE
Feature request: comparison of Maps via include

### ISSUE THREAD

**Issue by whawker** [astorije/chai-immutable#82]
In vanilla Chai, you can assert that a JS object includes all properties (and values) of another obj
i.e.
```js
expect({a: 1, b: 2, c: 3}).to.include({b: 2, c: 3});
```

Would it be possible to add a similar feature to chai-immutable for comparing Maps? 

Potentially `isSuperset` could be used(?), or perhaps each key/value pair would need to be compared individually.

Vanilla chai behaviour, for reference: https://jsbin.com/cihiteyoyu/2/edit?html,js,output

**Comment by dmonego** [comment]
This (or another function that behaves like it) would be tremendously useful. My use case is converting over a medium size codebase (~200 or so tests across a couple repos) that does a mix of converting to non immutable data and then using include, or using core immutable functions and just testing against booleans, leaving unreadable results.

I have a PR that makes this include behave like the standard chai include, and would welcome any feedback.

**Comment by astorije** [comment]
@whawker, @dmonego, can you confirm #177 (released in v2.0.0) resolves this issue?

**Comment by dmonego** [comment]
Working great! Thanks.
