### ISSUE TITLE
npm WARN chai-immutable@1.6.0 requires a peer of chai@>= 2.0.0 < 4 but none was installed.

### ISSUE THREAD

**Issue by mikeaustin** [astorije/chai-immutable#84]
Is there support for chai@4.0.2?

$ npm install --save-dev chai-immutable
models@1.0.0 /Library/WebServer/Documents/www.mike-austin.com/models
├── UNMET PEER DEPENDENCY chai@4.0.2
└── chai-immutable@1.6.0 

npm WARN chai-immutable@1.6.0 requires a peer of chai@>= 2.0.0 < 4 but none was installed.

**Comment by astorije** [comment]
Hi @mikeaustin,

Support for Chai v4 is underway, but not quite ready yet. In the meantime, there is a pre-release that might just work, you can install it with `npm install --save-dev chai-immutable@next`.

I'll keep this issue open until I am done with chai-immutable v2, that will fully support Chai v4.

**Comment by Fl4m3Ph03n1x** [comment]
Any news with this ?

**Comment by astorije** [comment]
Hi @Fl4m3Ph03n1x!
Sorry, no news at the moment, you need to use the v2.0.0-alpha.1 version for now, which should be sufficiently functional.
I'm planning to get back to that ASAP, apologies! 🙏

**Comment by Fl4m3Ph03n1x** [comment]
By no means I am not demanding, I was just curious on the progress. For me, this plugin is an integral part of using Immutable. If I can't have this plugin, I can't use Immutable, that's why I was asking. 

Thanks for the answering!

**Comment by astorije** [comment]
Gotcha @Fl4m3Ph03n1x. I didn't take your message as demanding, don't worry :) I feel bad for not wrapping this up earlier. Still in my short-term plans though!

In the meantime, you can add `"chai-immutable": "2.0.0-alpha.1"` or `"chai-immutable": "next"` to the `devDependencies` of your `package.json` file and that should be enough to use with Chai v4 :)

**Comment by astorije** [comment]
Alright, #69 got merged. This doesn't mean `chai-immutable` v2 (for Chai v4) is ready yet, and I'll do my best to clear this ASAP, but in the meantime, this issue is closed 🎉

**Comment by astorije** [comment]
Hey @mikeaustin and @Fl4m3Ph03n1x, I have just released [v2.0.0-rc.1](https://github.com/astorije/chai-immutable/releases/tag/v2.0.0-rc.1) which hopefully is the last step before full Chai v4 support (_finally!_). Mind giving it a shot and letting me know if it works as expected for you?

**Comment by Fl4m3Ph03n1x** [comment]
We stopped using Immutable altogether when we realized we couldn't have chai for it :p ( among other reasons ). 

I am afraid I can't test, as I have no setup for it.

**Comment by astorije** [comment]
I'm sorry to hear this and that it took me so long to get my ducks in a row, @Fl4m3Ph03n1x!
Well, if you happen to use Immutable again, at least this v2 will make it less of a pain to deal with the ecosystem!
Thanks for the quick reply :)
