### ISSUE TITLE
Investigate potential remaining items for Chai v4 support

### ISSUE THREAD

**Issue by astorije** [astorije/chai-immutable#86]
A long, long time ago, I listed a few things to look at to be ready for Chai v4 here: https://github.com/astorije/chai-immutable/pull/69#issuecomment-267802626

Need to wrap these.

**Comment by probedb** [comment]
Is there any update on version 2?

**Comment by astorije** [comment]
Hi @probedb! I stiiiill haven't finished this, I'm sorry. I'm almost there, there are a couple things left I want to look at before publishing this. Sorry about this!

In the meantime, I have just published `v2.0.0-alpha.2` with the latest `master`. It is compatible with Chai v4 and requires Node v6+. Could you try it (`npm install --save-dev chai-immutable@next` or `yarn add --dev chai-immutable@next`) and let me know if you notice anything wrong with it?

Thanks!

**Comment by astorije** [comment]
@probedb, any luck?

**Comment by astorije** [comment]
Hey @probedb, I have just released [v2.0.0-rc.1](https://github.com/astorije/chai-immutable/releases/tag/v2.0.0-rc.1) which hopefully is the last step before full Chai v4 support (_finally!_). Mind giving it a shot and letting me know if it works as expected for you?

**Comment by probedb** [comment]
Sorry @astorije ended up busy! I've updated to 2.0.0-rc.2 and chai 4.1.2 and the only issues I have are: when doing:

`expect(callback.args[0][0]).to.eql(new Error('something went wrong'))`

I get:

```javascript
AssertionError: expected [Error: something went wrong] to deeply equal [Error: something went wrong]
      + expected - actual
```

But I've had this before with error objects, there's 13 errors like this after the update.

**Comment by astorije** [comment]
I suspect this is unrelated to `chai-immutable` (or `immutable` itself), therefore not with the v2 either. Do you concur?

**Comment by probedb** [comment]
@astorije yep I'd agree, I believe it's due to the way the object is created for comparison and something has changed in Chai.
