### ISSUE TITLE
Cannot find module 'immutable'

### ISSUE THREAD

**Issue by forgo** [astorije/chai-immutable#89]
I am upgrading my package dependencies, including chai-immutable to 1.6.0, and I am getting this error upon running my code:

```
Error: Cannot find module 'immutable'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Assertion (/Users/elliott/Documents/GitHub/onestop/client/node_modules/chai-immutable/chai-immutable.js:8:30)
    at Object.<anonymous> (/Users/elliott/Documents/GitHub/onestop/client/node_modules/chai-immutable/chai-immutable.js:18:2)
```

As far as I can tell, chai-immutable handles 'immutable' as a dependency in it's own package.json. So why is it barfing here, suddenly?

I have done a `rm -rf` on my node_modules directory and reinstalled via `npm -i` before running, for the record.

**Comment by astorije** [comment]
Hi @forgo!

Do you have some relevant code you could provide? It's hard for me to see what's going on right now :)

> As far as I can tell, chai-immutable handles 'immutable' as a dependency in it's own package.json. So why is it barfing here, suddenly?

npm v... 5, I think, changed how they store dependencies and dependencies of dependencies. Did you happen to upgrade Node or npm since the last time you upgraded `chai-immutable`?

**Comment by forgo** [comment]
The error line is in node_modules/chai-immutable/chai-immutable.js:8:30.

The stacktrace tells me that this error is encountered where my code is simply importing 'chai-immutable':

**specHelper.js:3:1**
```javascript
import 'babel-polyfill'
import chai from 'chai'
import chaiImmutable from 'chai-immutable'
```

**Comment by astorije** [comment]
Is `immutable` listed in your dependencies? As of v2, it will be marked as a `peerDependencies, but it wasn't in v1.x, sorry.

**Comment by forgo** [comment]
I explicitly added immutable (version seen in node_module/chai-immutable's package.json:

```javascript
"devDependencies": {
  ...
  "immutable": "3.7.5",
  ...
}
```

Does this need to be made a peerDependency in your repo?
[NPM Peer Dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/)

**Comment by forgo** [comment]
Ha! You beat me to it. I think we are on the same page now. Thanks for looking at it.

**Comment by astorije** [comment]
Sure thing! Now I'm wondering if on top of the `peerDependencies` addition, `immutable` for this repo shouldn't be moved to from `devDependencies` to `dependencies`.
I need to look if doing so still requires projects that use it to have `immutable` in their dependencies because if so, I cannot do that.
